config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :astros, except: %i[index create] do
    collection do
      get :listed_astros
    end
    resources :bookings, only: %i[new create]
  end

  resources :astros, only: %i[create]

  # post 'astros', to: 'astros#index'
  resources :astros, only: %i[index]

  resources :bookings, only: %i[index] do
    collection do
      get :hosted_astros
    end
  end

  put 'confirm_booking/:id', as: :confirm_booking, to: 'bookings#confirm'
  put 'reject_booking/:id', as: :reject_booking, to: 'bookings#reject'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/astro.rb
class Astro < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user

  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_astros, against: [:name, :body_type, :around_planet, :discovered_by]

  validates :name, :body_type, :price, presence: true
  validates :name, uniqueness: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :astro

  validates :check_in, :check_out, presence: true, uniqueness: true
  validates :status, presence: true

  # accept or reject the bookings request ...
  enum status: { Pending: 0, Confirmed: 1, Rejected: 2 }

  def confirm!
    self.update(status: 1)
  end

  def reject!
    self.update(status: 2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :astros, dependent: :destroy
  has_many :bookings_as_owner, through: :astros, source: :bookings

  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pagy::Backend
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/astros_controller.rb
class AstrosController < ApplicationController
  before_action :set_astro, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[show index]

  def index
    if params[:query].present?
      # @astros = Astro.search_astros(params[:query])
      @pagy, @astros = pagy(policy_scope(Astro.search_astros(params[:query])))
    else
      # @astros = Astro.all
      @pagy, @astros = pagy(policy_scope(Astro))
    end

    respond_to do |format|
      format.html
      format.json {
        render json: { entries:render_to_string(partial:'astros', formats:[:html]), pagination:view_context.pagy_bootstrap_nav(@pagy) }
      }
    end
  end

  def show
    authorize @astro
    @booking = Booking.new
    # description = Astronomy::Information.new.search '#{@astro.name}'
    # astro_info = Astronomy::Information.new.search "Uranus"
    # astro_info.each { |astro| puts astro["description"] if astro["name"] == "Uranus" }
  end

  def new
    @astro = Astro.new
    authorize @astro
  end

  def create
    @astro = Astro.new(astro_params)
    @astro.user = current_user
    authorize @astro
    if @astro.save
      redirect_to astro_path(@astro), notice: "Astro was successfully listed!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @astro
  end

  def update
    authorize @astro
    @astro.update(astro_params)
    if @astro.save
      redirect_to astro_path(@astro), notice: "Astro was successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    authorize @astro
    @astro.destroy
    redirect_to astros_path, status: :see_other
  end

  # to see all the astros that have been listed by the current user ...
  def listed_astros
    @astros = current_user.astros
  end

  private

  def set_astro
    @astro = Astro.find(params[:id])
  end

  def astro_params
    params.require(:astro).permit(:name,
                                  :body_type,
                                  :around_planet,
                                  :description,
                                  :mass_value,
                                  :volume,
                                  :average_temperature,
                                  :density,
                                  :gravity,
                                  :mean_radius,
                                  :discovered_by,
                                  :discovered_date,
                                  :image_url,
                                  :photo,
                                  :price,
                                  )
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_astro_id, only: %i[new create]
  before_action :set_booking, only: %i[destroy]

  # all bookings made by the current user ...
  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.astro = @astro
    @booking.user = current_user
    authorize @booking
    @booking.status = "Pending"
    if @booking.save!
      redirect_to bookings_path, notice: "Your bookings was created. Waiting for host confirmation ..."
    else
      render :new, notice: "Booking unavailable. Please, check the dates."
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to root_path
  end

  def hosted_astros
    @bookings = current_user.bookings_as_owner
    authorize @bookings
  end

  def confirm
    booking = Booking.find(params[:id])
    authorize booking
    booking.confirm!
    redirect_to hosted_astros_bookings_path, notice: "Request was confirmed!"
  end

  def reject
    booking = Booking.find(params[:id])
    authorize booking
    booking.reject!
    redirect_to hosted_astros_bookings_path, notice: "Request was rejected!"
  end

  private

  def set_astro_id
    @astro = Astro.find(params[:astro_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/astros/_astros.html.erb
<% @astros.each do |astro|%>
  <div class="card-body bg-transparent">
      <%= image_tag "moon.jpg", class: "card-img mb-3", crop: :fill %>
      <div class="card-info">
        <p class="mx-2 mb-1"><strong>Name:</strong> <%= astro.name %></p>
        <p class="mx-2 mb-1"><strong>Body type:</strong> <%= astro.body_type %></p>
        <p class="mx-2 mb-1"><strong>Mass value:</strong> <%= astro.mass_value %></p>
        <p class="mx-2 mb-1"><strong>Avg temperature:</strong> <%= astro.average_temperature %></p>
        <p class="mx-2 mb-1"><strong>Volume:</strong> <%= astro.volume %></p>
        <p class="mx-2 mb-1"><strong>Density:</strong> <%= astro.density %></p>
        <p class="mx-2 mb-1"><strong>Gravity:</strong> <%= astro.gravity %></p>
        <p class="mx-2 mb-3"><strong>Mean radius:</strong> <%= astro.mean_radius %></p>
        <p class="price-info mx-2 mb-1"><strong>Price:</strong> <%= astro.price %>A$$</p>
        <% if astro.user != current_user  %>
          <%= link_to "Book now!", new_astro_booking_path(astro), class: "btn btn-space mt-4" %>
          <%= link_to "More info", astro_path(astro), class: "btn btn-space mt-4" %>
        <% else %>
          <%= link_to "More info", astro_path(astro), class: "btn btn-space mt-4" %>
        <% end %>

      </div>
  </div>
<% end %>

app/views/astros/edit.html.erb
<div class="container d-flex justify-content-start align-items-center" style="padding-top: 180px">
  <div class="form-fields">
    <h1 class="mb-4 mt-1">Update your astro!</h1>
    <%= simple_form_for(@astro) do |f| %>
      <%= f.input :name %>
      <%= f.input :body_type %>
      <%= f.input :around_planet %>
      <%= f.input :description %>
      <%= f.input :mass_value %>
      <%= f.input :volume %>
      <%= f.input :average_temperature %>
      <%= f.input :density %>
      <%= f.input :gravity %>
      <%= f.input :mean_radius %>
      <%= f.input :discovered_by %>
      <%= f.input :discovered_date %>
      <%= f.input :image_url %>
      <%= f.input :photo, as: :file %>
      <%= f.input :price %>
      <%= f.submit "Update", class: "btn btn-space mt-1 mb-4" %>
    <% end %>
  </div>
</div>
<div class="d-flex justify-content-end">
  <%= button_to "Back to all astros!", astros_path, method: :get, class: "btn btn-space mb-4 me-5" %>
</div>

app/views/astros/index.html.erb
<div class="container my-5 py-5">
  <div class="row justify-content-center my-4 py-5">
    <div class="col-6">
      <%= form_with url: astros_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control me-1",
          placeholder: "Find an astro to rent ..."
        %>
        <%= submit_tag "AstroSearch", class: "btn btn-space" %>
      <% end %>
    </div>
  </div>
  <div data-controller="infinite-scroll" data-action="scroll@window->infinite-scroll#scroll">
    <div class="cards mx-5" id="astros" data-infinite-scroll-target="entries">
      <%= render 'astros' %>
    </div>
    <div class="pag-bar mt-5 pt-5" data-infinite-scroll-target="pagination">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/astros/listed_astros.html.erb
<div class="container my-5 py-5">

    <div class="cards mx-5 my-5" id="astros">
      <% @astros.each do |astro|%>
        <div class="card-body bg-transparent">
            <%= image_tag "moon.jpg", class: "card-img mb-3", crop: :fill %>
            <div class="card-info">
              <p class="mx-2 mb-1"><strong>Name:</strong> <%= astro.name %></p>
              <p class="mx-2 mb-1"><strong>Body type:</strong> <%= astro.body_type %></p>
              <p class="mx-2 mb-1"><strong>Mass value:</strong> <%= astro.mass_value %></p>
              <p class="mx-2 mb-1"><strong>Avg temperature:</strong> <%= astro.average_temperature %></p>
              <p class="mx-2 mb-1"><strong>Volume:</strong> <%= astro.volume %></p>
              <p class="mx-2 mb-1"><strong>Density:</strong> <%= astro.density %></p>
              <p class="mx-2 mb-1"><strong>Gravity:</strong> <%= astro.gravity %></p>
              <p class="mx-2 mb-3"><strong>Mean radius:</strong> <%= astro.mean_radius %></p>
              <p class="price-info mx-2 mb-1"><strong>Price:</strong> <%= astro.price %>A$$</p>
              <%= link_to "Edit", new_astro_booking_path(astro), class: "btn btn-space mt-4" %>
              <%= link_to "Delete", astro_path(astro), class: "btn btn-space mt-4" %>
            </div>
        </div>
      <% end %>
    </div>

</div>

app/views/astros/new.html.erb
<div class="container d-flex justify-content-start align-items-center" style="padding-top: 180px">
  <div class="form-fields">
    <h1 class="mb-4 mt-1">List your astro!</h1>
    <%= simple_form_for(@astro) do |f| %>
      <%= f.input :name %>
      <%= f.input :body_type %>
      <%= f.input :around_planet %>
      <%= f.input :description %>
      <%= f.input :mass_value %>
      <%= f.input :volume %>
      <%= f.input :average_temperature %>
      <%= f.input :density %>
      <%= f.input :gravity %>
      <%= f.input :mean_radius %>
      <%= f.input :discovered_by %>
      <%= f.input :discovered_date %>
      <%= f.input :image_url %>
      <%= f.input :photo, as: :file %>
      <%= f.input :price %>
      <%= f.button :submit, "List astro", data: { turbo_method: :post }, class: "btn btn-space mt-1 mb-4" %>
    <% end %>
  </div>
</div>
<%# <div class="d-flex justify-content-end">
  <%= button_to "Back to all astros!", astros_path, method: :get, class: "btn btn-space mb-4 me-5" %>
<%# </div> %>

app/views/astros/show.html.erb
<div class="container mt-5 py-5" style="min-height: 95vh">
  <div class="row justify-content-evenly my-4 py-5">

    <div class="col-5">
      <%= image_tag "moon.jpg", class: "astro-img", crop: :fill %>
    </div>

    <div class="col-5 ">
      <h1 class="astro-name mb-4 font-weight-bold"><%= @astro.name %></h1>
      <p class="show-data my-2"><strong>Body type: </strong><%= @astro.body_type%></p>
      <p class="show-data my-2"><strong>Around planet: </strong><%= @astro.around_planet%></p>
      <p class="show-data my-2"><strong>Mass value: </strong><%= @astro.mass_value%></p>
      <p class="show-data my-2"><strong>Avg temperature: </strong><%= @astro.average_temperature%></p>
      <p class="show-data my-2"><strong>Volume: </strong><%= @astro.volume%></p>
      <p class="show-data my-2"><strong>Density: </strong><%= @astro.density%></p>
      <p class="show-data my-2"><strong>Gravity: </strong><%= @astro.gravity%></p>
      <p class="show-data my-2"><strong>Mean radius: </strong><%= @astro.mean_radius%></p>
      <p class="show-data my-2"><strong>Discovered by: </strong><%= @astro.discovered_by%></p>
      <p class="show-data my-2"><strong>Discovered on: </strong><%= @astro.discovered_date%></p>
      <p class="show-data show-price my-4"><strong>Price: <%= @astro.price%> A$$ per day</strong></p>

      <% if @astro.user != current_user %>
        <%= link_to "Book now!", new_astro_booking_path(@astro), class: "btn btn-space mt-4" %>
      <% else %>
        <%= link_to "Edit", edit_astro_path(@astro), class: "btn btn-space mt-2 me-2" %>
        <%= link_to "Delete", astro_path(@astro), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{@astro.name}?" }, class: "btn btn-space mt-2 ms-2" %>
      <% end %>
    </div>

  </div>
</div>

app/views/bookings/hosted_astros.html.erb
<div class="container" style="padding-top: 100px;">
  <h1 class="mx-5 my-5">Astros rented:</h1>
  <div class="cards mx-5">
    <% @bookings.each do |booking|%>
      <div class="card-body bg-transparent">
        <%= image_tag "moon.jpg", class: "card-img mb-3", crop: :fill %>
        <div class="card-info">
          <h4 class="mx-2 mb-3"><%= booking.astro.name %></h4>
          <p class="mx-2 mb-1"><strong>Check in:</strong> <%= booking.check_in %></p>
          <p class="mx-2 mb-1"><strong>Check out:</strong> <%= booking.check_out %></p>
          <p class="mx-2 mb-1"><strong>Status:</strong> <%= booking.status %></p>
        </div>
        <div class="d-flex justify-content-evenly">
          <a class="button"><%= button_to "Confirm", confirm_booking_path(booking), params: {booking: booking}, method: :put, class: "btn btn-space mt-5"%></a>
          <a class="button"><%= button_to "Reject", reject_booking_path(booking), params: {booking: booking}, method: :put, class: "btn btn-space mt-5" %></a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container" style="padding-top: 100px;">
  <h1 class="mx-5 my-5">All your bookings:</h1>
  <div class="cards mx-5">
    <% @bookings.each do |booking|%>
      <div class="card-body bg-transparent">
        <%= image_tag "moon.jpg", class: "card-img mb-3", crop: :fill %>
        <div class="card-info">
          <h4 class="mx-2 mb-3"><%= booking.astro.name %></h4>
          <p class="mx-2 mb-1"><strong>Check in:</strong> <%= booking.check_in %></p>
          <p class="mx-2 mb-1"><strong>Check out:</strong> <%= booking.check_out %></p>
          <p class="mx-2 mb-1"><strong>Status:</strong> <%= booking.status %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container d-flex justify-content-start align-items-center" style="min-height: 92vh; padding-top: 0px">
  <div class="form-fields">
    <h1 class="mb-4 mt-1">Rent <%= @astro.name %> right now!</h1>
    <%= simple_form_for([@astro, @booking]) do |f| %>
      <%= f.input :check_in %>
      <%= f.input :check_out %>
      <p class="fs-5 mt-4">Price (per day): <strong><%= @astro.price %> A$$</strong></p>
      <p class="fs-5 my-3">Total days: <strong> ### </strong></p>
      <p class="fs-5 mb-4">Booking total: <strong> ### A$$</strong></p>
      <%= f.submit "Book now!", class: "btn btn-space mt-1 mb-4" %>
      <% end %>
  </div>
</div>
<div class="d-flex justify-content-end">
  <%= button_to "Back to all astros!", astros_path, method: :get, class: "btn btn-space mb-4 me-5" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Axtrous</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="page-container">
      <%= render "shared/navbar" %>
      <main id="main-content">
        <%= yield %>
      </main>
      <%# <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/my/bookings/index.html.erb
<div class="container" style="padding-top: 100px;">
  <h1 class="mx-5 my-5">All your astros bookings:</h1>
  <div class="cards mx-5">
    <% @astros.each do |astro| %>
    <% astro.bookings.each do |booking|%>
      <div class="card-body bg-transparent">
        <%= image_tag "moon.jpg", class: "card-img mb-3", crop: :fill %>
        <div class="card-info">
          <h4 class="mx-2 mb-3"><%= booking.astro.name %></h4>
          <p class="mx-2 mb-1"><strong>Check in:</strong> <%= booking.check_in %></p>
          <p class="mx-2 mb-1"><strong>Check out:</strong> <%= booking.check_out %></p>
          <p class="mx-2 mb-1"><strong>Status:</strong> <%= booking.status %></p>
        </div>
        <div class="status-update mt-3">
          <div class="status-confirm">
            <%= link_to "Confirm", my_bookings_path(booking: {status: "Confirmed"}), method: :patch, class: "my-2 btn btn-space" %>
          </div>
          <div class="status-confirm">
            <%= link_to "Reject", my_bookings_path(booking: {status: "Canceled"}), method: :patch, class: "my-2 btn btn-space" %>
          </div>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/pages/about.html.erb
<div class="container pt-5 d-flex justify-content-start align-items-center" style="min-height: 100vh; background-image: url(https://res.cloudinary.com/dgjvosgwy/image/upload/v1672664108/bg2_cb6axn.jpg);">

</div>

app/views/pages/contact.html.erb
<div class="container pt-5 d-flex justify-content-start align-items-center" style="min-height: 100vh; background-image: url(https://res.cloudinary.com/dgjvosgwy/image/upload/v1672664108/bg2_cb6axn.jpg);">

</div>

app/views/pages/home.html.erb
<div class="container pt-5 d-flex justify-content-start align-items-center" style="min-height: 100vh; background-image: url(https://res.cloudinary.com/dgjvosgwy/image/upload/v1672664108/bg2_cb6axn.jpg);">
  <div class="call-to-action ms-5 py-5 px-5">
    <h1 class="slogan">Extend your limits,<br>travel the galaxy,<br>rent your astro.</h1>
    <% if user_signed_in? %>
      <%= link_to "Explore", astros_path, class: "btn btn-space mt-5" %>
    <% else %>
      <%= link_to "Explore", new_user_session_path, class: "btn btn-space mt-5" %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer fixed-bottom bg-transparent">
  <div class="footer-copyright">
    Created by Giovanni Barros
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dgjvosgwy/image/upload/v1672673293/astrouslogo1_yu5hg3.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "AstroSearch", astros_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "New astro", new_astro_path, class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "My booked astros", hosted_astros_bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-space nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>